# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pwnCheck.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(481, 320)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(481, 320))
        MainWindow.setMaximumSize(QtCore.QSize(481, 320))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 481, 321))
        self.tabWidget.setToolTip(_fromUtf8(""))
        self.tabWidget.setStyleSheet(_fromUtf8("Log\n"
"color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 255), stop:0.19397 rgba(0, 0, 0, 255), stop:0.202312 rgba(122, 97, 0, 255), stop:0.495514 rgba(76, 58, 0, 255), stop:0.504819 rgba(255, 255, 255, 255), stop:0.79 rgba(255, 255, 255, 255), stop:1 rgba(255, 158, 158, 255));\n"
"color: rgb(174, 255, 239);\n"
"font: 75 italic 9pt \"Noto Sans\";"))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.mainTab = QtGui.QWidget()
        self.mainTab.setObjectName(_fromUtf8("mainTab"))
        self.checkButton = QtGui.QPushButton(self.mainTab)
        self.checkButton.setGeometry(QtCore.QRect(380, 150, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkButton.setFont(font)
        self.checkButton.setObjectName(_fromUtf8("checkButton"))
        self.resultLabel = QtGui.QLabel(self.mainTab)
        self.resultLabel.setGeometry(QtCore.QRect(10, 190, 451, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(10)
        self.resultLabel.setFont(font)
        self.resultLabel.setFrameShape(QtGui.QFrame.Panel)
        self.resultLabel.setFrameShadow(QtGui.QFrame.Sunken)
        self.resultLabel.setText(_fromUtf8(""))
        self.resultLabel.setTextFormat(QtCore.Qt.RichText)
        self.resultLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.resultLabel.setWordWrap(True)
        self.resultLabel.setObjectName(_fromUtf8("resultLabel"))
        self.infoLabel = QtGui.QLabel(self.mainTab)
        self.infoLabel.setGeometry(QtCore.QRect(10, 10, 451, 131))
        self.infoLabel.setObjectName(_fromUtf8("infoLabel"))
        self.passwordLineEdit = QtGui.QLineEdit(self.mainTab)
        self.passwordLineEdit.setGeometry(QtCore.QRect(10, 150, 361, 29))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.passwordLineEdit.setFont(font)
        self.passwordLineEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.passwordLineEdit.setAutoFillBackground(True)
        self.passwordLineEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.passwordLineEdit.setReadOnly(False)
        self.passwordLineEdit.setObjectName(_fromUtf8("passwordLineEdit"))
        self.tabWidget.addTab(self.mainTab, _fromUtf8(""))
        self.logTab = QtGui.QWidget()
        self.logTab.setAutoFillBackground(False)
        self.logTab.setObjectName(_fromUtf8("logTab"))
        self.logScrollArea = QtGui.QScrollArea(self.logTab)
        self.logScrollArea.setGeometry(QtCore.QRect(0, 1, 471, 281))
        self.logScrollArea.setWidgetResizable(True)
        self.logScrollArea.setObjectName(_fromUtf8("logScrollArea"))
        self.logScroll = QtGui.QWidget()
        self.logScroll.setGeometry(QtCore.QRect(0, 0, 469, 279))
        self.logScroll.setObjectName(_fromUtf8("logScroll"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.logScroll)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.logLabel = QtGui.QLabel(self.logScroll)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(8)
        self.logLabel.setFont(font)
        self.logLabel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.logLabel.setFrameShadow(QtGui.QFrame.Plain)
        self.logLabel.setTextFormat(QtCore.Qt.LogText)
        self.logLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.logLabel.setWordWrap(True)
        self.logLabel.setObjectName(_fromUtf8("logLabel"))
        self.horizontalLayout_2.addWidget(self.logLabel)
        self.logScrollArea.setWidget(self.logScroll)
        self.tabWidget.addTab(self.logTab, _fromUtf8(""))
        self.aboutTab = QtGui.QWidget()
        self.aboutTab.setObjectName(_fromUtf8("aboutTab"))
        self.tabWidget_2 = QtGui.QTabWidget(self.aboutTab)
        self.tabWidget_2.setGeometry(QtCore.QRect(20, 30, 441, 241))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.descriptionTab = QtGui.QWidget()
        self.descriptionTab.setObjectName(_fromUtf8("descriptionTab"))
        self.descriptionScrollArea = QtGui.QScrollArea(self.descriptionTab)
        self.descriptionScrollArea.setGeometry(QtCore.QRect(0, -1, 441, 211))
        self.descriptionScrollArea.setWidgetResizable(True)
        self.descriptionScrollArea.setObjectName(_fromUtf8("descriptionScrollArea"))
        self.descriptionScroll = QtGui.QWidget()
        self.descriptionScroll.setGeometry(QtCore.QRect(0, 0, 439, 209))
        self.descriptionScroll.setObjectName(_fromUtf8("descriptionScroll"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.descriptionScroll)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.descriptionLabel = QtGui.QLabel(self.descriptionScroll)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.descriptionLabel.setFont(font)
        self.descriptionLabel.setText(_fromUtf8(""))
        self.descriptionLabel.setTextFormat(QtCore.Qt.RichText)
        self.descriptionLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.descriptionLabel.setWordWrap(True)
        self.descriptionLabel.setObjectName(_fromUtf8("descriptionLabel"))
        self.horizontalLayout_3.addWidget(self.descriptionLabel)
        self.descriptionScrollArea.setWidget(self.descriptionScroll)
        self.tabWidget_2.addTab(self.descriptionTab, _fromUtf8(""))
        self.changelogTab = QtGui.QWidget()
        self.changelogTab.setObjectName(_fromUtf8("changelogTab"))
        self.tabWidget_2.addTab(self.changelogTab, _fromUtf8(""))
        self.bugsTab = QtGui.QWidget()
        self.bugsTab.setObjectName(_fromUtf8("bugsTab"))
        self.tabWidget_2.addTab(self.bugsTab, _fromUtf8(""))
        self.licenseTab = QtGui.QWidget()
        self.licenseTab.setObjectName(_fromUtf8("licenseTab"))
        self.licenseScrollArea = QtGui.QScrollArea(self.licenseTab)
        self.licenseScrollArea.setGeometry(QtCore.QRect(0, 0, 441, 211))
        self.licenseScrollArea.setWidgetResizable(True)
        self.licenseScrollArea.setObjectName(_fromUtf8("licenseScrollArea"))
        self.licenseScroll = QtGui.QWidget()
        self.licenseScroll.setGeometry(QtCore.QRect(0, 0, 439, 209))
        self.licenseScroll.setObjectName(_fromUtf8("licenseScroll"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.licenseScroll)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.licenseLabel = QtGui.QLabel(self.licenseScroll)
        self.licenseLabel.setTextFormat(QtCore.Qt.PlainText)
        self.licenseLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.licenseLabel.setObjectName(_fromUtf8("licenseLabel"))
        self.horizontalLayout.addWidget(self.licenseLabel)
        self.licenseScrollArea.setWidget(self.licenseScroll)
        self.tabWidget_2.addTab(self.licenseTab, _fromUtf8(""))
        self.headerLabel = QtGui.QLabel(self.aboutTab)
        self.headerLabel.setGeometry(QtCore.QRect(40, 0, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.headerLabel.setFont(font)
        self.headerLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.headerLabel.setAutoFillBackground(False)
        self.headerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.headerLabel.setObjectName(_fromUtf8("headerLabel"))
        self.tabWidget.addTab(self.aboutTab, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.checkButton, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.tabWidget_2)
        MainWindow.setTabOrder(self.tabWidget_2, self.licenseScrollArea)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "pwnCheck", None))
        self.tabWidget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\">Log</p></body></html>", None))
        self.checkButton.setText(_translate("MainWindow", "Check", None))
        self.infoLabel.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">How this program works:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:296;\">1. SHA1 hash calculated of  a password.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:296;\">2. Prefix variable is set to first 5 symbols of the hash.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:296;\">3. All hashes with matching prefix are pulled from </span><span style=\" font-weight:296; font-style:italic;\">pwnedpasswords.com DB</span><span style=\" font-weight:296;\">.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:296;\">4. Password hash match checked </span><span style=\" font-weight:600;\">localy</span><span style=\" font-weight:296;\"> on users PC.</span></p></body></html>", None))
        self.passwordLineEdit.setPlaceholderText(_translate("MainWindow", "Enter password", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mainTab), _translate("MainWindow", "Main", None))
        self.logLabel.setText(_translate("MainWindow", "TextLabel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.logTab), _translate("MainWindow", "Log", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.descriptionTab), _translate("MainWindow", "Description", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.changelogTab), _translate("MainWindow", "Changelog", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.bugsTab), _translate("MainWindow", "Known bugs", None))
        self.licenseLabel.setText(_translate("MainWindow", "TextLabel", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.licenseTab), _translate("MainWindow", "License", None))
        self.headerLabel.setText(_translate("MainWindow", "Password pwn checking GUI", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.aboutTab), _translate("MainWindow", "About", None))

